#!/bin/bash

set -o errexit
set -o nounset


celery -A config.celery flower \
    --broker="${REDIS_URL}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}" \
    --address=0.0.0.0 \
    --port=5555 \
    --persistent=True \
    --auto_refresh=True \
    --logging_level=DEBUG
