# Generated by Django 6.0.6 on 2026-06-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='region',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
