# Generated by Django 6.0.6 on 2026-06-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_enrollment_grade_alter_enrollment_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('region', 'Region'), ('grade', 'Grade')], db_index=True, max_length=128)),
                ('key_value', models.CharField(max_length=128)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollment__region_eb9f36_idx',
        ),
        migrations.AddIndex(
            model_name='enrollmentcounter',
            index=models.Index(fields=['key_type', 'key_value'], name='enrollment__key_typ_ff65a3_idx'),
        ),
    ]
